Add operations
jackwish/tflite2onnx pull request #21
Opened 2020-11-03 15:23 UTC by IkbeomJeon

- Tranpose convolution
see decription : https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvTranspose

- Sigmoid
It is refered to 'Logistic' in your Operation Code. I understand it is sigmoid fuction. see : https://github.com/onnx/onnx/blob/master/docs/Operators.md#Sigmoid

2020-11-03 15:33 UTC, IkbeomJeon commented
and Thanks your contributions.  :)

2020-11-04 01:29 UTC, jackwish requested changes
Hi @IkbeomJeon thank you for contributing these operators! Finally, I won't write the code all by my own, that means a lot!

I go through this PR quickly and leave several comments. In general
* We spare efforts to keep this repo small enough, the model files is the most significant
  * We plan to track end-to-end models in [`more-model-test branch`](https://github.com/jackwish/tflite2onnx/tree/more-model-test) branch, maybe we can exclude the network model from this PR?
  * The tensor size of the operator can be small. This requires to re-generate yet another TFLite model per operator, yes, I know this could be boring.
* We let CI track our development to ease the maintenance effort
  * Every TFLite operator should have its own unit test, i.e. dedicated TFLite model that contains the operator only. Could you help to have one for Sigmoid?
  * Code style is guarded by `Flake8`, just type `flake8`, it will tell you where to fix.

I know our guide is out of date, I have a plan to fix it this or next week. Thank you again for your effort!

2020-11-04 01:29 UTC, jackwish commented on tests/test_models.py
> +        'conv-transpose_relu.float32',
I typically name the files with `-` as the delimiter, i.e. `op-op-op.<dtype>`

2020-11-04 01:29 UTC, jackwish commented on tests/test_models.py
> +        'object_detection_3d_sneakers',
In most cases, I'd like to keep the `master` branch small enough. That means, we keep only test purpose operator TFLite model on `master` branch, and track more network-wide models in [`more-model-test`](https://github.com/jackwish/tflite2onnx/tree/more-model-test) branch. I can help to move this model to that branch after this PR got merged.

2020-11-04 01:29 UTC, jackwish commented on tests/test_models.py
> +
Maybe remove this blank line?

2020-11-04 01:29 UTC, jackwish commented on tflite2onnx/op/conv_transpose.py
> +import logging
What about including the `ConvTranspose` class in `tflite2onnx/op/conv.py` as it's an altered version of Conv somehow. Maybe we can even share to utils just like [Pooling](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/pooling.py).

2020-11-04 01:29 UTC, jackwish commented on tflite2onnx/op/logistic.py
> +        pass
GitHub warns  _No newline at the end of file_, it seems to me some editors may contribute this :)

2020-11-04 01:30 UTC, jackwish commented
I have changed the title to better demonstrate what is in this PR. Feel free to change into any format you like.

2020-11-04 04:06 UTC, jackwish commented on tflite2onnx/op/logistic.py
> +import logging
Btw, we can include activation operators that don't have attributes in one converter class in https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/activation.py,  but let me handle that.

2020-11-07 11:44 UTC, IkbeomJeon commented
Okay, I'll try as soon as possible. :)

2020-11-19 12:53 UTC, jackwish commented
@IkbeomJeon I have merged your change with the latest master branch. I was planning to push to your `add_op` branch, but it seems I am not able to push. Did you enable the _allow modify of maintainer_ option for this PR? Alternatively, I pushed to my [`deconv`](https://github.com/jackwish/tflite2onnx/tree/deconv) branch, you can pull and merge to your `add_op` branch.

There must be something wrong with padding handling in the current code since my tiny model is failing while a `stride == 2` can pass. We can continue to work on it.

2020-11-22 14:47 UTC, jackwish commented
I have reworked the code:
* Drop operators that have been enabled
* Move `TransposeConv` to `conv.py`
* Drop paths that have not been tested
* Code style fix

After the test pass, I will merge this PR.

2020-11-22 14:54 UTC, jackwish commented
TODO of `TransposeConv` (due to we do not fully understand the semantic gap)
1. Special output shape for VALID padding
2. Different input/output shape for SAME padding

2020-11-22 14:56 UTC, jackwish approved these changes
The test passes, merge as initial support. TODO tracked by https://github.com/jackwish/tflite2onnx/issues/26#issuecomment-731760320

2020-11-22 14:57 UTC, merged