Removing newline in description to comply with pypa/setuptools#1390
jackwish/tflite2onnx pull request #55
Opened 2021-01-17 09:52 UTC by paulgavrikov

See issue #49

2021-01-17 15:03 UTC, jackwish reviewed
Let's remove the _real description_ if we are going to make it one line.

2021-01-17 15:03 UTC, jackwish commented on tflite2onnx/__init__.py
> +DESCRIPTION = 'Convert TensorFlow Lite models to ONNX models. ' \
```suggestion
DESCRIPTION =  "tflite2onnx v%s, https://github.com/jackwish/tflite2onnx" % VERSION
```

2021-01-17 15:03 UTC, jackwish commented on tflite2onnx/__init__.py
> +              'tflite2onnx v%s, https://github.com/jackwish/tflite2onnx' % VERSION
```suggestion
```

2021-01-18 07:23 UTC, paulgavrikov commented
I'd do it the other way round and kickout the url. [setuptools](https://packaging.python.org/guides/distributing-packages-using-setuptools/#description) states "Give a short and long description for your project.". But ultimately it is up to you of course!

2021-01-18 11:16 UTC, jackwish commented
@paulgavrikov By _share the pip package you built_ I mean upload to the discussion issue #49. We don't include wheel in our code.

For the URL part, I was suggested to do that. As people can easily search for it, I agree that we can remove it to just left the name, version, and a short description.

2021-01-18 15:02 UTC, jackwish requested changes

2021-01-18 15:02 UTC, jackwish commented on tflite2onnx/__init__.py
> +DESCRIPTION =  "tflite2onnx v%s, Convert TensorFlow Lite models to ONNX" % VERSION
```suggestion
DESCRIPTION = "tflite2onnx v%s, Convert TensorFlow Lite models to ONNX" % VERSION
```

2021-01-18 15:09 UTC, jackwish approved these changes

2021-01-18 15:09 UTC, merged