'Leaky_Relu' op suuport
jackwish/tflite2onnx pull request #63
Opened 2021-03-23 04:52 UTC by shilpan97

hey, wasn't sure if my changes are correct(please treat as initial attempt). 
When trying to run on my machine I got the following error message:
AttributeError: type object 'ActivationFunctionType' has no attribute 'LEAKY_RELU'. 
Not sure how to fix it. 

Please feel free to edit directly. 
Thanks!

2021-03-23 05:07 UTC, shilpan97 commented
formula:
f(x) = alpha * x for x < 0 , f(x) = x for x >= 0

2021-03-23 14:00 UTC, jackwish requested changes
@shilpan97 Thanks for contributing to the project! I am very pleased that we received a new contribution after the last release.

I left several comments in the PR. In general (just like what we mentioned in the [how to enable new operator tutorial](https://github.com/jackwish/tflite2onnx/blob/master/docs/how-to-enable-new-operator.md)), we'd like to attach the test (including the TFLite model which contains the operator only if possible, and the test code) in our code change, such that we know what functionality is working and what needs to be fixed whenever we make a change.

This can be done since we have written a detailed guide of enabling operators. Please feel free to raise any question about the document or the enabling.

Thanks!

2021-03-23 23:46 UTC, shilpan97 reviewed
Changes based on previous feedback. I don't think I can give my .tflite to you unfortunately due to permissions. Hopefully this changes fix it. Thank you! Also, can you let me know when are you pushing your next release thanks. Earlier would be great.

2021-03-23 23:51 UTC, shilpan97 reviewed
removed from act_type

2021-03-24 00:21 UTC, jackwish requested changes
Thanks for the update! By ***testing*** I mean create a new TFLite model which contains the operator (`LeakyReLU` for this case) only, so there is no legal issue. The guide includes every step to do this, I believe you will have a better understanding of this tool if read through it.

2021-03-24 00:21 UTC, jackwish commented on tflite2onnx/op/activation.py
> +            alpha = option.Alpha()
The alpha needs to be passed to the ONNX operator. The code here actually does nothing. The `Concat` code may tip you how to do it.

2021-03-24 11:13 UTC, jackwish commented
@shilpan97 You can take a look at this PR https://github.com/jackwish/tflite2onnx/pull/25/files which implements the `Prelu` which should be very similar to your work.

2021-04-13 23:35 UTC, closed without merging